baseURL = "https://mojtabaseyedi.com/"
languageCode = "en"
title = "Mojtaba Seyedi"
#disqusShortname = "mojtabaseyedi"
googleAnalytics = ""
theme = "moji"
pygmentsCodefences = true
pygmentsStyle = "monokailight"
[params]
  author = "مجتبی سیدی"
  [params.socials]
    twitter = "https://twitter.com/mojtabaseyedi"
    codepen = "https://codepen.io/seyedi"
    linkedin = "https://ir.linkedin.com/pub/mojtaba-seyedi/61/157/1a"
    github = "https://github.com/seyedi"
