baseURL = "https://seyedi.github.io/"
languageCode = "fa-IR"
title = "مجتبی سیدی"
disqusShortname = "mojtabaseyedi"
googleAnalytics = ""
theme = "moji"
pygmentsCodefences = true
pygmentsStyle = "monokailight"
[params]
  author = "مجتبی سیدی"
  layoutDirection = "rtl"
